version: "3.9"

services:
  simulation:
    container_name: simulation
    image: ghcr.io/jakubczech/agv-simulation-ros2-gazebo:main
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv
    env_file:
      - ./docker_env.env

  controller:
    container_name: controller
    image: ghcr.io/jakubczech/agv-controller:main
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv
    restart: always
    env_file:
      - ./docker_env.env

  navigation:
    container_name: navigation
    image: ghcr.io/jakubczech/agv-navigation:main
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv
    restart: always
    env_file:
      - ./docker_env.env

  servo:
    container_name: servo
    image: ghcr.io/jakubczech/ros2_kinco_servo:main
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv
    restart: always
    env_file:
      - ./docker_env.env

  visualization:
    container_name: visualization
    image: ghcr.io/jakubczech/agv-remote:main
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv
    env_file:
      - ./docker_env.env
