version: "3.9"

services:
  simulation:
    container_name: simulation
    image: ghcr.io/jakubczech/agv-simulation-ros2-gazebo:main
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv
    environment:
      - DISPLAY=$DISPLAY
      - GAZEBO_GUI=$GAZEBO_GUI

  controller:
    container_name: controller
    image: ghcr.io/jakubczech/agv-controller:main
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv

  navigation:
    container_name: navigation
    image: ghcr.io/jakubczech/agv-navigation:main
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv

  servo:
    container_name: servo
    image: ghcr.io/jakubczech/ros2_kinco_servo:main
    environment:
      - SERVO_PORT=$SERVO_PORT
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv

  visualization:
    container_name: visualization
    image: ghcr.io/jakubczech/agv-remote:main
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv
    environment:
      - DISPLAY=$DISPLAY
