version: "3.9"

services:
  simulation:
    container_name: simulation
    image: ghcr.io/jakubczech/agv-simulation-ros2-gazebo:main
    environment:
      - DISPLAY=$DISPLAY
      - GAZEBO_GUI=$GAZEBO_GUI
    volumes:
      - /dev:/dev:ro
      - ./AGV-Simulation-ROS2-Gazebo/src_files/src/agv_simulation:/root/workspace/src/agv_simulation:rw
      - ./AGV-Simulation-ROS2-Gazebo/scripts/ros2_build.sh:/root/workspace/ros2_build.sh:rw
      - ./AGV-Simulation-ROS2-Gazebo/scripts/rebuild_model.sh:/root/workspace/rebuild_model.sh:rw
      - ./AGV-Simulation-ROS2-Gazebo/scripts/entrypoint.sh:/root/workspace/entrypoint.sh:rw
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv

  controller:
    container_name: controller
    image: ghcr.io/jakubczech/agv-controller:main
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /dev:/dev:ro
      - ./AGV-Controller/src_files/src:/root/workspace/src:rw
      - ./AGV-Controller/scripts/entrypoint.sh:/root/workspace/entrypoint.sh:rw
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv

  navigation:
    container_name: navigation
    image: ghcr.io/jakubczech/agv-navigation:main
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /dev:/dev:ro
      - ./AGV-Navigation/src_files/src/agv_navigation:/root/workspace/src/agv_navigation:rw
      - ./AGV-Navigation/src_files/src/agv_planner:/root/workspace/src/agv_planner:rw
      - ./AGV-Navigation/src_files/src/agv_controller:/root/workspace/src/agv_controller:rw
      - ./AGV-Navigation/scripts/entrypoint.sh:/root/workspace/entrypoint.sh:rw
    depends_on:
      - simulation
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv

  servo:
    container_name: servo
    image: ghcr.io/jakubczech/ros2_kinco_servo:main
    environment:
      - DISPLAY=$DISPLAY
      - SERVO_PORT=$SERVO_PORT
    volumes:
      - /dev:/dev:ro
      - ./ROS2_Kinco_Servo/src_files/src/kinco_driver:/root/workspace/src/kinco_driver:rw
      - ./ROS2_Kinco_Servo/scripts/entrypoint.sh:/root/workspace/entrypoint.sh:rw
    depends_on:
      - simulation
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv
