version: "3.9"

services:
  simulation:
    container_name: simulation
    image: ghcr.io/jakubczech/agv-simulation-ros2-gazebo:main
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /dev:/dev:ro
      - ./AGV-Simulation-ROS2-Gazebo/src/agv_simulation:/root/workspace/src/agv_simulation:rw
      - ./AGV-Simulation-ROS2-Gazebo/scripts/ros2_build.sh:/root/workspace/ros2_build.sh:rw
      - ./AGV-Simulation-ROS2-Gazebo/scripts/rebuild_model.sh:/root/workspace/rebuild_model.sh:rw
      - ./AGV-Simulation-ROS2-Gazebo/scripts/entrypoint.sh:/root/workspace/entrypoint.sh:rw
    entrypoint:
      - /root/workspace/entrypoint.sh
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv

  # controller:
  #   container_name: controller
  #   image: ghcr.io/jakubczech/agv-controller:main
  #   environment:
  #     - DISPLAY=$DISPLAY
  #   volumes:
  #     - /dev:/dev:ro
  #     - ./AGV-Controller/src/odometry:/root/workspace/src/odometry:rw
  #     - ./AGV-Controller/src/controller:/root/workspace/src/controller:rw
  #     - ./AGV-Controller/src/scan:/root/workspace/src/scan:rw
  #     - ./AGV-Controller/scripts/entrypoint.sh:/root/workspace/entrypoint.sh:rw
  #   entrypoint:
  #     - /root/workspace/entrypoint.sh
  #   tty: true
  #   stdin_open: true
  #   privileged: true
  #   network_mode: host
  #   hostname: agv

  navigation:
    container_name: navigation
    image: ghcr.io/jakubczech/agv-navigation:main
    # image: agv:navigation
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /dev:/dev:ro
      - ./AGV-Navigation/src/agv_navigation:/root/workspace/src/agv_navigation:rw
      - ./AGV-Navigation/src/agv_planner:/root/workspace/src/agv_planner:rw
      - ./AGV-Navigation/src/agv_controller:/root/workspace/src/agv_controller:rw
      - ./AGV-Navigation/scripts/entrypoint.sh:/root/workspace/entrypoint.sh:rw
    entrypoint:
      - /root/workspace/entrypoint.sh
    depends_on:
      - simulation
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    hostname: agv
