teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1  # Left thumb stick vertical
      y: 0  # Left thumb stick horizontal
    scale_linear:
      x: 0.1
      y: 0.1
    scale_linear_turbo:
      x: 0.3
      y: 0.3

    axis_angular:  # Right thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 0.025
    scale_angular_turbo:
      yaw: 0.5

    enable_button: 2  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
